#
# Autogenerated by Sandesh Compiler (1.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

from vr_nldump.pysandesh.Thrift import TType, TMessageType, TException
from vr_nldump.pysandesh.gen_py.sandesh.ttypes import *

SANDESH_KEY_HINT = 1
SANDESH_CONTROL_HINT = 2
SANDESH_SYNC_HINT = 4
